= Welcome to Component B!

This is the automatic start page for version *{page-component-version}* of Component B.

Component B is one of two documentation components in the Antora Demo.
The other docs component, Component A, can be accessed via the component selector menu (aka component drawer) at the bottom of the menu on the left side of the page.

== Page source

This page is sourced from the AsciiDoc file named [.path]_index.adoc_ that is located at [.path]_demo-component-b/docs/modules/ROOT/pages_.

=== Why is this the home page of Component B?

This page is automatically used as the start page of Component B because it is stored in the ROOT module and named [.path]_index.adoc_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the ROOT module of Component B*, the xref syntax would be `\xref:index.adoc[]`.

To create a cross reference *to this page from a page in Module One of Component B*, the xref syntax would be `\xref:ROOT:index.adoc[]`.

To create a cross reference *to this page from a page in Component A*, the xref syntax would be `\xref:1.0@component-b::index.adoc[]`.
